import Link from "next/link";
import { createManager, deleteManager, updateManager } from "@/app/admin/user-actions";
import { requireOwner } from "@/lib/auth";
import { getAdminSitesForUser, getAdminUsersWithAccess } from "@/lib/queries";

export default async function UsersPage() {
  const owner = await requireOwner();
  const [users, sites] = await Promise.all([getAdminUsersWithAccess(), getAdminSitesForUser(owner)]);
  return <main className="admin-shell"><header className="admin-topbar"><div><Link href="/admin">← Siteler</Link><span className="eyebrow">YETKİLENDİRME</span><h1>Kullanıcılar</h1><p>Müşteri veya ekip hesabına yalnızca seçtiğiniz siteleri açın.</p></div></header><div className="admin-grid"><section className="panel"><div className="admin-subhead"><h2>Manager ekle</h2></div><form action={createManager} className="stack-form"><label>E-posta<input name="email" type="email" required /></label><label>Geçici parola<input name="password" type="password" minLength={10} required /></label><fieldset className="category-checks"><legend>Site erişimi</legend>{sites.map((site) => <label className="check" key={site.id}><input type="checkbox" name="siteIds" value={site.id} /> {site.name}</label>)}</fieldset><button className="button primary" type="submit">Manager oluştur</button></form></section><section className="panel wide"><div className="admin-subhead"><h2>Hesaplar</h2><span className="count">{users.length}</span></div><div className="section-list">{users.map((user) => <div className="user-card" key={user.id}><div className="user-card-head"><div><strong>{user.email}</strong><br /><small>{user.role} · {user.lastLoginAt ? `son giriş ${user.lastLoginAt.toLocaleString("tr-TR")}` : "henüz giriş yok"}</small></div><span className="status-pill">{user.role}</span></div>{user.role === "manager" ? <><form action={updateManager} className="stack-form"><input type="hidden" name="userId" value={user.id} /><fieldset className="category-checks"><legend>Site erişimi</legend>{sites.map((site) => <label className="check" key={site.id}><input type="checkbox" name="siteIds" value={site.id} defaultChecked={user.siteIds.includes(site.id)} /> {site.name}</label>)}</fieldset><label>Yeni parola <small>(boş bırakılırsa değişmez)</small><input name="password" type="password" minLength={10} /></label><button className="button ghost" type="submit">Erişimi kaydet</button></form><form action={deleteManager}><input type="hidden" name="userId" value={user.id} /><button className="button danger" type="submit">Manager sil</button></form></> : <p className="admin-help">Owner tüm sitelere ve kullanıcı yönetimine erişir.</p>}</div>)}</div></section></div></main>;
}
